# Generated by Django 3.2.15 on 2022-08-09 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 8, 9, 18, 42, 14, 593871, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
