# Generated by Django 3.2.15 on 2022-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
